# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’

target 'SampleSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLoggly’
  # pod 'SwiftCSVExport'

   pod 'SwiftCSVExport', :git => 'https://github.com/vigneshuvi/SwiftCSVExport.git', :tag => '2.6.0'

  # Pods for SampleSwift

  target 'SampleSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
